### ISSUE TITLE
"Yapeal.Cache.cacheDir" returns InvalidArgumentException when using Database:Init

### ISSUE THREAD

**Issue by sredbull** [Yapeal/yapeal-ng#1]
[InvalidArgumentException]

Identifier "Yapeal.Cache.cacheDir" is not defined.

I got this when trying to initialize my DB. I created a config/yapeal.yaml

**Comment by Dragonrun1** [comment]
Looks like I have a reversed ternary in Configuration\Wiring::wireConfig().
