### ISSUE TITLE
yc Database:Init not installing

### ISSUE THREAD

**Issue by Isfirs** [Yapeal/yapeal-ng#4]
I'm having this feedback from running the command above:

> C:\xampp\htdocs\Laravel_Yapeal-NG\vendor\yapeal\yapeal-ng\bin>php yc Database:Init
> 
> C:/xampp/htdocs/Laravel_Yapeal-NG/vendor/yapeal/yapeal-ng/lib/Sql/Database/CreateDatabase.sql
> C:/xampp/htdocs/Laravel_Yapeal-NG/vendor/yapeal/yapeal-ng/lib/Sql/Api/CreateCallList.sql
> 
>  [Yapeal\Exception\YapealDatabaseException]
>  -- Sql/Api/CreateCallList.sql
>  -- version 20160201053352.424
>  CREATE TABLE "yapeal"."apiCallList" (
>      "description" TEXT NOT NULL,
>      "groupID" BIGINT(20) UNSIGNED NOT NULL,
>      "name" CHAR(100) NOT NULL,
>      PRIMARY KEY ("groupID")
>  )
>  Sql failed in C:/xampp/htdocs/Laravel_Yapeal-NG/vendor/yapeal/yapeal-> ng/lib/Sql/Api/CreateCallList.sql on statement
>   0 with (42S01) SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'apicalllist' already > exists
> 
> Database:Init [-c|--configFile CONFIGFILE] [-d|--database DATABASE] [-o|--hostName HOSTNAME] > [-p|--password PASSWORD] [-
> -platform PLATFORM] [--port PORT] [-t|--tablePrefix TABLEPREFIX] [-u|--userName USERNAME]

Environment:
- Windows 7
- XAMPP 7.0

I noticed, I can't find the related SQL files in the lib/Sql/Util

**Comment by Dragonrun1** [comment]
If you tried running yc D:I twice you can end up with that error if you didn't drop the database or all of Yapeal's tables before trying it again. BTW you'll find the SQL files where it says they are in the error message lib/Sql/*/. The error message I get says:

Sql failed in D:/repos/github/yapeal-ng/lib/Sql/Util/CreateCachedUntil.sql on statement 0 with (42S01) SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'utilcacheduntil' already exists

if I run it a second time. Are you sure that you didn't do that as well?

**Comment by Dragonrun1** [comment]
Since have received a response to question I'm closing issue.
